### ISSUE TITLE
Bookmarks vs marks

### ISSUE THREAD

**Issue by georgeguimaraes** [chentoast/marks.nvim#107]
Hi, thanks for the plugin. I'm using it a lot with marks (especially "asdf" marks).
However, what's the difference between regular marks and bookmarks (0-9)? I couldn't find a documentation in a glance.

**Comment by chentoast** [comment]
There's not much of a difference. But bookmarks have the advantage of being "grouped". So you could cycle through all bookmarks of group 1 using the same key, whereas with marks, you need to remember the exact alphabetical key to jump to the mark location

**Comment by georgeguimaraes** [comment]
ahh got it!

I need to provide my own mapping for next_bookmark0, next_bookmark1, ..., right? I can see now that there are `m}` and `m{`, but I can't see how I can access my bookmarks inside a group with the default config.
