### ISSUE TITLE
`:delmarks` does not permanently delete marks

### ISSUE THREAD

**Issue by bruhtus** [chentoast/marks.nvim#13]
AFAIK, there's still a problem with `:delmarks` that doesn't really delete the mark which you can see here: https://github.com/neovim/neovim/issues/4295.

So, I want to ask, is the `:delmarks` bug already been fix or did you use another approach to hide the deleted marks in sign column?

If it's already been fixed, then that's good. If it's not, maybe you should give an information about that to prevent someone creating an issue that's not related to the plugin.

Thank you.

**Comment by chentau** [comment]
No, this bug still exists, and is definitely quite annoying. If i have some free time I may and try my hand at fixing it.

there are two workarounds that I’m aware of:

- Set your shada file to not serialize mark information, so lowercase marks are lost after quitting vim.
- Use the ‘force_write_shada’ flag in the setup function, which overwrites the shada file after mark deletion. Be careful when setting this! It could cause you to lose information.

**Comment by QianquanChina** [comment]
Even if I set **force_write_shada = true**, there is still a small problem, and this **dm\<space>** command can sometimes be deleted and sometimes cannot be deleted. But  **dm[ - or a - z ...]**  command is running normally

**Comment by Cris-lml007** [comment]
Hopefully soon they will solve that shada problem, the use of brands helps developers a lot and having to delete all the marks to remove just one does not seem quite good to me, I love this plugin, so I do not place double marks or I am constantly opening: marks

**Comment by chentoast** [comment]
fyi: for those that are following this issue, I have a pr in the works (https://github.com/neovim/neovim/pull/16067) that will resolve this issue. Please follow that PR if you want to track its progress.

**Comment by nicolimo86** [comment]
I installed the plugin today (branch: master, commit:76aca50) and i still see the marks reappearing after their deletion when I reopen the file.

**Comment by Cris-lml007** [comment]
in which version this solution will be added?

**Comment by jthvai** [comment]
@Cris-lml007 neovim/neovim#24936 is part of the (Neovim) [0.10 milestone](https://github.com/neovim/neovim/milestone/36), which has a due date of April 01, 2024.

**Comment by aemonge** [comment]
Isn't the issue that uppercase marks are "system" ones? 

If so, can we filter out the uppercase marks on the number column?
