### ISSUE TITLE
Feature Request: Ability to control sign priority

### ISSUE THREAD

**Issue by andrewferrier** [chentoast/marks.nvim#14]
In NeoVim, one can control the 'priority' of signs in the sign column. (See `:help sign-priority`). It would be nice if I could control the priority of the signs `marks.nvim` places in its configuration. For example, I use `gitsigns.nvim` also, and I consider git changes to be more important than `marks.nvim` signs (sorry!). It would be nice to be able to 'demote' the signs from this plugin.

Even better (if this is not just creeping configuration) would be to control letter signs and built-in marks separately. The former I place myself, so they are arguably 'important'. The latter are by-products of editing, and I would argue should be very low priority.

**Comment by chentau** [comment]
Yes, this is on the todo list. My priority is first fixing #10 , but after that it should be relatively simply to add an option controlling this.
