### ISSUE TITLE
`setup()` with no param causes "config is nil" error

### ISSUE THREAD

**Issue by aj3423** [chentoast/marks.nvim#67]
When setup with `require('marks').setup()`,  it shows error:
![image](https://user-images.githubusercontent.com/4710875/168609776-4ee6548f-38b0-4920-b284-0c26e7d2b959.png)

`setup({})` fixes the problem, maybe could be better:
```lua
-- marks.nvim/lua/init.lua:191
function M.setup(config)
  config = config or {}  -- <----
--...
  M.mark_state.builtin_marks = config.builtin_marks or {}  <-- this causes error 
```
Just an advice, please close this anyway, thanks for the plugin.

**Comment by chentoast** [comment]
Should be an easy fix.
