### ISSUE TITLE
Hide marks by default

### ISSUE THREAD

**Issue by samuelevalperta** [chentoast/marks.nvim#76]
Hi,
Is it possible to not show marks by default and let them appear only when I use MarksToggleSigns?

**Comment by dinhmai74** [comment]
Any solution for this @samuelevalperta ?

**Comment by samuelevalperta** [comment]
> Any solution for this @samuelevalperta ?

I added this in my .vimrc
'''autocmd VimEnter * MarksToggleSigns'''.
It basically exec the command MarksToggleSigns once every time you enter vim.
