### ISSUE TITLE
Any way to toggle bookmarks same way we can toggle marks?

### ISSUE THREAD

**Issue by lawrence-laz** [chentoast/marks.nvim#90]
For marks toggling we have `<Plug>(Marks-toggle)`, but for bookmarks we have separate add and remove:
```
<Plug>(Marks-set-bookmark[0-9])
<Plug>(Marks-delete-bookmark[0-9])
```
Is it possible to have something like `<Plug>(Marks-toggle-bookmark[0-9])`?

**Comment by chentoast** [comment]
closed by #91
